### PR TITLE
Deliver assets form different (external) hosts

### PR DESCRIPTION
**Pull request by sebastian-alfers**
What do you think?

### CODE REVIEW

**Comment by edeustace** [comment]
Cheers - I'll have a look at it over the weekend

**Comment by sebastian-alfers** [comment]
Thanks!

**Comment by sebastian-alfers** [comment]
Any comments about this?

**Comment by edeustace** [comment]
Sorry @sebastian-alfers  - had a busy weekend - will look tonight

**Comment by edeustace** [comment]
Hi @sebastian-alfers, just been looking through it now. It seems to me that the host resolution feature you have added and deployment are related and that it may make sense to enhance the deployment feature to provide support for path resolution as well as deployment.

The current deployer should only deploy, and we can then allow a resolver to be passed in to the Loader.

pseudo code: 

```
trait ExternalAssets {
  def deployer : Deployer //as it is now
  def resolver : Resolver
}
/**
 * The loader will resolve the path to the asset using this trait instead of the internal FileToWebPath
 */
trait Resolver {
  def resolve(filename:String, lastModified:DateTime) : String
}

val externalAssets = new ExternalAssets{
   def deployer = new Deployer{ .... }
   def resolver = new Resolver {
     def resolve(filename:String, lastModified:DateTime) : String = {
        //any resolution logic can now be applied..

      }
   }
}
new com.ee.assets.Loader(Some(externalAssets), ..., ...)
```

I'm kind of thinking out loud - but I think it'll help cement the relationship between deployment and host resolution. thoughts?

**Comment by sebastian-alfers** [comment]
Thanks for your comments!
First I thought about touching the deployer logic, but in my opinion it is already made for implementing a own custom host path like in your example-app.
Also, one can make usage of the hosts rotation-logic from his custom deployer.

I will update my pull request with an example now.

What do you think?

**Comment by edeustace** [comment]
The hosts resolution only runs in the FileToWebPath, but if you are deploying then this isn't used. How do you deploy and resolve hosts in the same application instance? I can see that you can use the ExternalHosts as in your last commit, but I think that assets-loader should have a single entry point and the rest of the library should be inaccessible.

**Comment by sebastian-alfers** [comment]
Good point! I added the logic to resolve the host during deploy and give the user the chance to override that process. Any comments on this @edeustace ?

**Comment by sebastian-alfers** [comment]
Any chance to approve it?

**Comment by edeustace** [comment]
Sorry Sebastian - been running around the last few days...  will have a
look this eve.

On Tue, Jul 22, 2014 at 10:46 AM, Sebastian Alfers <notifications@github.com

**Comment by edeustace** [comment]
Hi @sebastian-alfers - so I was having a look at the PR, and I felt that the use case that this PR supports could be available if the assets-loader api changed in a small way.

 The benefit of this approach is it'll support this use case, plus any other that someone may think of without having to bake it into this library. The PR is here: #36. I'll add some detail there as to what it entails. Of note for this PR is how it recreates the ExternalHosts functionality in the example app: https://github.com/edeustace/assets-loader/blob/34-sebastian-alfers-alternate-approach/example/example-play-app/app/views/Helper.scala#L58

**Comment by edeustace** [comment]
See #36

**Pull request closed without merging**
